=== jackpay/SemanticSearchAnalysisEngine/conf/configuration.dtd
<!ELEMENT configuration (solr-config,mysql-config,nutch-seedlist,nutch-blacklist,mysql-input-tables,mysql-output-tables,column-fields,mysql-fieldvalues,fieldvalue-class)>
<!ELEMENT solr-config (url,key-field,solr-user,solr-pass)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT key-field (#PCDATA)>
<!ELEMENT solr-user (#PCDATA)>
<!ELEMENT solr-pass (#PCDATA)>
<!ELEMENT mysql-config (port,database,mysql-user,mysql-pass,mysql-key-field,server)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT mysql-user (#PCDATA)>
<!ELEMENT mysql-pass (#PCDATA)>
<!ELEMENT mysql-key-field (#PCDATA)>
<!ELEMENT server (#PCDATA)>
<!ELEMENT nutch-seedlist (new-seeds-loc,file-loc)>
<!ELEMENT nutch-blacklist (field,file-loc)>
<!ELEMENT new-seeds-loc (#PCDATA)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT file-loc (#PCDATA)>
<!ELEMENT mysql-input-tables (table*)>
<!ELEMENT mysql-output-tables (table*)>
<!ELEMENT table (#PCDATA)>
<!ELEMENT column-fields (column-field*)>
<!ELEMENT column-field (field,column)>
<!ELEMENT field (#PCDATA)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT recipients (recipient*)>
<!ELEMENT recipient (email)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT nutch-query (nutch-fv*)>
<!ELEMENT nutch-fv (field,value)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT m51-query (m51-fv*)>
<!ELEMENT m51-fv (field,value)>
<!ELEMENT mysql-fieldvalues (field-value*)>
<!ELEMENT field-value (fv-table,fv-field,fv-value)>
<!ELEMENT fv-table (#PCDATA)>
<!ELEMENT fv-field (#PCDATA)>
<!ELEMENT fv-value (#PCDATA)>
<!ELEMENT fieldvalue-class (#PCDATA)>

=== jackpay/SemanticSearchAnalysisEngine/conf/globalstudies-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!-- 

##########################################################################################
##########
########## Default configuration file to configure the GlobalStudiesPollingService.
##########
########## All "Required" fields must be provided.
##########
########## author: jackpay date: 20/10/2014
##########
##########################################################################################

-->
<configuration>

	<!-- Used to specify Solr server configuration details -->
	<solr-config>
		<!-- Required -->
		<url>http://localhost:8983/solr</url>
		<key-field>id</key-field>
		
		<!-- Optional: depending on Solr configuration. -->
		<solr-user></solr-user>
		<solr-pass></solr-pass>
		
	</solr-config>

	<!-- Used to specify MySQL configuration details -->
	<mysql-config>
	
		<!-- Required -->
		<port>3306</port>
		<database>solr-method51</database>
		<mysql-user>jp242</mysql-user>
		<mysql-pass>BoLlocks6</mysql-pass>
		<mysql-key-field>url</mysql-key-field>
		<server>localhost</server>
		
	</mysql-config>
	
	<!-- Nutch seedlist configurations -->
	<nutch-seedlist>
		<new-seeds-loc>/Volumes/LocalDataHD/jp242/Documents/Projects/GlobalStudies/Implementation/nutch-global/runtime/local/bin/seedAdd.txt</new-seeds-loc>
		<file-loc>/Volumes/LocalDataHD/jp242/Documents/Projects/GlobalStudies/Implementation/nutch-global/runtime/local/bin/seed.txt</file-loc>
	</nutch-seedlist>
	
	<!-- Nutch blacklist configurations -->
	<nutch-blacklist>
		<field>url</field>
		<file-loc>/Volumes/LocalDataHD/jp242/Documents/Projects/GlobalStudies/apache-nutch-1.8/runtime/local/conf/regex-urlfilter.txt</file-loc>
	</nutch-blacklist>
	
	<!-- Used to specify MySQl input tables to sent the Solr search results to. -->
	<mysql-input-tables>
		<table>tweets-solrmethod51</table>
	</mysql-input-tables>
	
	<!-- Used to specify a list of MySQL output tables to poll for classification results. -->
	<!-- TODO: Attribute: significant class tables, i.e. email stats-->
	<mysql-output-tables>
		<table>tweets-solrmethod51-relevant</table>
		<table>tweets-solrmethod51-irrelevant</table>
	</mysql-output-tables>
	
	<!-- Stores corresponding MySQL columns and Solr fields. -->
	<!-- TODO: Attribute: key field indicator (plus defaults) -->
	<column-fields>
		<column-field>
			<field>id</field>
			<column>url</column>
		</column-field>
		<column-field>
			<field>content</field>
			<column>text</column>
		</column-field>
	</column-fields>
	
	<!-- A list of email recipients to send details of the classification run. -->
	<recipients>
		<recipient>
			<email>jp242@sussex.ac.uk</email>
		</recipient>
		<recipient>
			<email>jackpay84@googlemail.com</email>
		</recipient>
	</recipients>
	
		<!-- The query field/value pairs used to query Solr for documents to add to the blacklist. -->
	<nutch-query>
		<nutch-fv>
			<field>analyst-relevant</field>
			<value>false</value>
		</nutch-fv>
	</nutch-query>
	
	<!-- The query field/value pairs used to query Solr for documents to send to Method51. -->
	<m51-query>
		<m51-fv>
			<field>parsed</field>
			<value>false</value>
		</m51-fv>
		<m51-fv>
			<field>-sentence</field>
			<value>null</value>
		</m51-fv>
		<m51-fv>
			<field>lang</field>
			<value>en</value>
		</m51-fv>
	</m51-query>
	
	<!-- Used to specify a list of MySQL column names and corresponding Solr field/value pairs.
		 Used to provide details of field/value pairs updates in solr. 
		 If this is not expressive enough a FieldValueFactory can be used instead. / -->
	<mysql-fieldvalues>
		<field-value>
			<!-- MySQL table name. -->
			<fv-table></fv-table>
			<!-- Solr field. -->
			<fv-field></fv-field>
			<!-- Value to update Solr field. -->
			<fv-value></fv-value>
		</field-value>
	</mysql-fieldvalues>
	
	<!-- Used to specify the fully qualified classname of a class implementing IFieldValueFactory. -->
	<fieldvalue-class>ac.uk.susx.tag.fieldvalue.GlobalStudiesFieldValueFactory</fieldvalue-class>

</configuration>
